[workspace]
members = ["airup-sdk", "airupfx", "airupd", "airup", "airup-sdk-ffi"]
resolver = "2"

[profile.release]
lto = true

[workspace.dependencies.tokio]
version = "1"
features = ["fs", "sync", "net", "io-util", "signal", "rt", "time", "macros", "rt-multi-thread", "process"]