[package]
name = "airupfx-io"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.10.4"
edition = "2024"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
