[package]
name = "airup-eventsourced"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.9.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
airup-sdk = { path = "../airup-sdk", features = ["_internal"] }
anyhow = "1"
tokio = { workspace = true }
serde_json = "1"
