[package]
name = "airupfx-time"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.9.2"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
