[package]
name = "airupfx"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.2.0"
edition = "2021"
license = "Unlicense"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
full = ["ace", "config", "files", "fs", "ipc", "log", "policy", "power", "process", "sdk", "time", "users"]
ace = ["users", "process"]
config = ["toml", "env"]
env = []
files = ["toml", "users", "fs"]
fs = []
ipc = ["serde_json"]
log = ["tracing-subscriber", "env"]
policy = ["fs", "users"]
power = ["process"]
process = []
sdk = ["ipc", "config", "files", "process"]
time = []
users = ["sysinfo", "caches"]

[dependencies]
async-trait = "0.1"
ahash = "0.8"
anyhow = "1"
caches = { version = "0.2", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
sysinfo = { version = "0.29", optional = true }
libc = "0.2"
thiserror = "1"
tokio = { workspace = true }
toml = { version = "0.7", optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["serde"], optional = true }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uneval = "0.2"