[package]
name = "airupfx"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.3.1"
edition = "2021"
license = "Unlicense"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
libc = "0.2"
moka = { version = "0.12", features = ["future"] }
once_cell = "1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.29"
thiserror = "1"
tokio = { workspace = true }
toml = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"