[package]
name = "airup-sdk"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.4.0"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1"
airupfx = { path = "../airupfx" }
libc = "0.2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.29"
tokio = { workspace = true }
toml = "0.7"
thiserror = "1"