[package]
name = "airup-sdk"
authors = ["sisungo <sisungo@icloud.com>"]
description = "SDK library of Airup"
documentation = "https://docs.rs/airup-sdk"
repository = "https://github.com/sisungo/airup"
version = "0.5.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[features]
_internal = []

[dependencies]
anyhow = "1"
ahash = "0.8"
json-patch = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { workspace = true }
toml = "0.7"
thiserror = "1"