[package]
name = "airup-sdk"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.3.1"
edition = "2021"
license = "Unlicense"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
airupfx = { path = "../airupfx" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { workspace = true }
toml = "0.7"
thiserror = "1"