[package]
name = "airupd"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.4.0-alpha.1"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
atomic_refcell = "0.1"
airupfx = { path = "../airupfx" }
airup-sdk = { path = "../airup-sdk" }
libc = "0.2"
once_cell = "1"
serde = "1"
serde_json = "1"
sysinfo = "0.29"
thiserror = "1"
tokio = { workspace = true }
toml = "0.7"
tracing = "0.1"