[package]
name = "airupd"
authors = ["sisungo <sisungo@icloud.com>"]
version = "0.3.1"
edition = "2021"
license = "Unlicense"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
airupfx = { path = "../airupfx" }
airup-sdk = { path = "../airup-sdk" }
libc = "0.2"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { workspace = true }
tracing = "0.1"